kcdc3/apps/classes/urls.py
from django.conf.urls import patterns, include, url
from models import Event, Registration
from views import EventListView, EventDetailView, ResponseTemplateView, EventArchiveView, SessionView, RegistrationListView, SessionAdminListView, TeacherAdminListView, FilteredTeacherAdminListView, UserEventListView, JSONVizSessionAttendanceDataListView, tsv_events_by_location_data, csv_users_data, SocialListView
urlpatterns = patterns('kcdc3.apps.classes.views',

	url(r'^$', EventListView.as_view()),

	# staff dashboard
	url(r'^staff/$', SessionAdminListView.as_view()),
	url(r'^staff/teachers/$', TeacherAdminListView.as_view()),
	url(r'^staff/teachers/session/(?P<slug>[A-Za-z0-9_-]+)/$', FilteredTeacherAdminListView.as_view()),
	url(r'^staff/registrations/session/(?P<slug>[A-Za-z0-9_-]+)/$', RegistrationListView.as_view()),
	url(r'^staff/social/session/(?P<slug>[A-Za-z0-9_-]+)/$', SocialListView.as_view()),

	# data
	url(r'^data/attendance/session/(?P<slug>[A-Za-z0-9_-]+)/json/$', JSONVizSessionAttendanceDataListView.as_view()),
	url(r'^data/attendance/session/(?P<slug>[A-Za-z0-9_-]+)/csv/$', 'csv_session_attendance_data'),
	url(r'^data/registration/session/(?P<slug>[A-Za-z0-9_-]+)/csv/$', 'csv_session_registration_data'),
	url(r'^data/location/txt/$', 'txt_location_data'),
	url(r'^data/location/json/$', 'json_location_data'),
	url(r'^data/event_location/json/$', 'json_event_location_data'),
	url(r'^data/events_by_location/tsv/$', 'tsv_events_by_location_data'),
	url(r'^data/users/csv/$', 'csv_users_data'),

	url(r'^classes$', UserEventListView.as_view()),

	url(r'^(?P<slug>[0-9_-]+)/$', EventArchiveView.as_view()),
	url(r'^(?P<slug>[0-9_-]+)/background/$', SessionView.as_view()),

	url(r'^response/(?P<slug>[A-Za-z0-9_-]+)$', ResponseTemplateView.as_view()),

	url(r'^(?P<slug>[A-Za-z0-9_-]+)/$', EventDetailView.as_view(model=Event,)),
	url(r'^(?P<slug>[A-Za-z0-9_-]+)/register$', 'register'),
	url(r'^(?P<slug>[A-Za-z0-9_-]+)/cancel$', 'cancel'),
	url(r'^(?P<slug>[A-Za-z0-9_-]+)/facilitator$', 'facilitator'),

)

kcdc3/urls.py
from django.conf.urls.defaults import *
from apps.accounts.views import SignupFormExtra
from filebrowser.sites import site
from django.conf import settings

# development
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

	url(r'^$', 'kcdc3.apps.pinata.views.home'),
	url(r'^classes/', include('kcdc3.apps.classes.urls')),
	url(r'^my/', include('kcdc3.apps.classes.urls')),
	url(r'^blog/', include('kcdc3.apps.pigeon.urls')),
	url(r'^teach/proposal/$', 'kcdc3.apps.pinata.views.proposal'),
	url(r'^about/$', 'kcdc3.apps.pinata.views.staff'),
	url(r'^about/partners/$', 'kcdc3.apps.pinata.views.partners'),
	url(r'^search/$', 'kcdc3.apps.pinata.views.search'),
	url(r'^press/$', 'kcdc3.apps.pinata.views.pressclippings'),
	url(r'^about/|teach/|contribute/|store/|special/|pr/', include('kcdc3.apps.pinata.urls')),
	url(r'^admin/filebrowser/', include(site.urls)),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^grappelli/', include('grappelli.urls')),
	url(r'^accounts/signup/$', 'userena.views.signup', {'signup_form': SignupFormExtra}),
	url(r'^accounts/', include('userena.urls')),
	url(r'^staff/', include('kcdc3.apps.squirrel.urls')),
	url('^markdown/', include( 'django_markdown.urls')),

)


if settings.DEBUG:
	urlpatterns += patterns('',
		url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': settings.MEDIA_ROOT,
		}),
		url(r'^assets/(?P<path>.*)$', 'django.views.static.serve', {
			'document_root': settings.ASSETS_ROOT,
		}),
   )

kcdc3/apps/classes/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from datetime import timedelta
from format_helpers import *
import random

# In hours, how long before a class do late promotion rules apply?
WAITLIST_LATE_PROMOTION_TIME = 24
CLASSES_IDEAL_STUDENT_MULTIPLIER = 0.667
RANDOM_GEOCODE_NOISE = 0.003

# a Session is a collection of classes
class Session(models.Model):
	title = models.CharField(max_length=200)
	long_title = models.CharField(max_length=200)
	slug = models.SlugField(unique=True)
	STATUS_CHOICES = (
		('CURRENT', 'Current'),
		('PAST', 'Past'),
		('HIDDEN', 'Hidden'),
	)
	status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='CURRENT')

	kicker = models.CharField('Kicker (for Classes page hed)', max_length=200, blank=True)
	description = models.TextField('Intro/Description', blank=True)
	sidebar_text = models.TextField('Sidebar', blank=True)
	show_sidebar_text = models.BooleanField(default=True)
	documentation = models.TextField('Documentation/Extended Text', blank=True)

	REGISTRATION_STATUS_CHOICES = (
		('ALLOW', 'Allow'),
		('PREVENT', 'Prevent'),
	)
	registration_status = models.CharField(max_length=7, choices=REGISTRATION_STATUS_CHOICES, default='PREVENT')
	email_reminder_days = models.IntegerField('Send reminder emails this many days ahead of classes:', default=2)

	class Meta:
		ordering = ['slug']

	def __unicode__(self):
		return self.title

	# Report regular, published classes
	def get_live_classes(self):
		return Event.objects.filter(session=self,status="PUBLISHED",type="CLASS")

	# Report regular, published classes
	def get_registrations(self):
		return Registration.objects.filter(event__session=self,cancelled=False,waitlist=False)

	# Report regular, published classes
	def get_attended_registrations(self):
		return Registration.objects.filter(event__session=self,cancelled=False,attended=True)




class Location(models.Model):
	name = models.CharField('Description', max_length=100, blank=True)
	neighborhood = models.CharField('Neighborhood', max_length=100, blank=True)
	address1 = models.CharField('Address', max_length=60, blank=True)
	address2 = models.CharField('Line two', max_length=60, blank=True)
	city = models.CharField('City', max_length=60, blank=True, default='Washington')
	state = models.CharField('State', max_length=2, blank=True, default='DC')
	zip = models.CharField('ZIP', max_length=5, blank=True)
	hint = models.CharField('Hint', max_length=300, blank=True)
	show_exact = models.BooleanField('Show details/exact address on public site?', default=True)
	LOCATION_ACCESS_CHOICES = (
		('public', 'Public'),
		('semipublic', 'Semi-Public'),
		('private', 'Private'),
	)
	access = models.CharField(max_length=11, choices=LOCATION_ACCESS_CHOICES, default='SEMIPUBLIC')
	lat = models.FloatField('Latitude',blank=True,null=True)
	lng = models.FloatField('Longitude',blank=True,null=True)
	
	def __unicode__(self):
		return self.name

	# add random noise to coordinates
	def add_noise_to_coord(self, coord, noise):
		return coord + random.uniform(-noise,noise)
		
	# return latitude, with random noise for locations for which show_exact is false
	def get_lat(self):
		lat = self.lat
		if not self.show_exact:
			lat = self.add_noise_to_coord(lat,RANDOM_GEOCODE_NOISE)
		return lat

	# return longitude, with random noise for locations for which show_exact is false
	def get_lng(self):
		lng = self.lng
		if not self.show_exact:
			lng = self.add_noise_to_coord(lng,RANDOM_GEOCODE_NOISE)
		return lng


# Organizations with whom KCDC is working
class Partner(models.Model):
	name = models.CharField('Name', max_length=100, blank=False, unique=True)
	description = models.TextField('Description', blank=True)
	website = models.URLField(blank=True)
	image = models.ImageField('Image (150x150px max)', upload_to='partners', blank=True, null=True)
	featured = models.BooleanField('Featured', default=True)

	class Meta:
		verbose_name=u'Location Partner'

	def __unicode__(self):
		return self.name



# A group that a person is part of
class Role(models.Model):
	
	name = models.CharField('Name', max_length=48)
	description = models.TextField(blank=True)
	extended_description = models.TextField(blank=True)
	sort_order = models.IntegerField(blank=True, null=True, default=50)

	class Meta:
		ordering = ['sort_order']
		verbose_name=u'Staff Team/Group'
		verbose_name_plural=u'Staff Teams/Groups'

	def __unicode__(self):
		return self.name

	



class Bio(models.Model):

	user = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, related_name='user')

	# Basic information, used in class descriptions and elsewhere by default
	name = models.CharField('Name', max_length=100, blank=False, unique=True)
	description = models.TextField('Bio text', blank=True)
	web = models.CharField('Website', max_length=255, blank=True)
	image = models.ImageField('Image (160x160px)', upload_to='bio', blank=True, null=True)
	staff_image = models.ImageField('Image (160x160px)', upload_to='staff_bio', blank=True, null=True)
	twitter = models.CharField('Twitter Handle', max_length=16, blank=True)
	show_email = models.BooleanField('Show email to public?', default=False)

	# No longer in use. Why? Because Django insists on adding a slash
	# to the end of URLFields, and defining my own field type seems excessive
	website = models.URLField(blank=True)

	# Fields for staff bios
	title = models.CharField(max_length=100, blank=True)
	staff_description = models.TextField('Staff bio text', blank=True)
	role = models.ForeignKey(Role, blank=True, null=True, on_delete=models.SET_NULL, related_name='role')

	# Fields for internal use
	rating = models.IntegerField('Rating', null=True, blank=True)
	comments = models.TextField('Comments', null=True, blank=True)
	bio_email = models.EmailField(null=True, blank=True)

	# Provide a filled-out description if one is available
	def get_staff_description(self):
		
		if self.staff_description:
			return self.staff_description
		else: 	
			return self.description

	# Provide Twitter handle with at-sign removed
	def get_twitter(self):
		tmp = self.twitter.replace("@","")
		return tmp

	# Provide website address; add http:// if no protocol is specified
	def get_web(self):
		return add_protocol(self.web)

	# Provide website with http:// removed
	def get_plain_web(self):
		return remove_protocol(self.web)

	# Provide email from bio; otherwise email from user
	def get_email(self):
		
		if self.bio_email:
			return self.bio_email
		elif self.user:
			return self.user.email
		else:
			return ""
	    		
	# Which classes is this person teaching?
	def get_classes(self):
		
		return Event.objects.filter(teacher_bios=self)
			
	class Meta:
		ordering = ['name']
		verbose_name=u'Teacher/Staff Bio'

	def __unicode__(self):
		return self.name



# an Event is a single class or other event
class Event(models.Model):
	
	# fundamentals
	title = models.CharField(max_length=200)
	slug = models.SlugField(unique=True)
	STATUS_CHOICES = (
		('PUBLISHED', 'Published'),
		('HIDDEN', 'Hidden'),
		('DRAFT', 'Draft'),
		('REMOVED', 'Removed'),
	)
	status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='PUBLISHED')
	cancelled = models.BooleanField(default=False)
	
	# show on front page
	featured = models.BooleanField(default=False)
	
	# dates
	session = models.ForeignKey(Session, blank=False, null=True, on_delete=models.SET_NULL, related_name='session')
	date = models.DateTimeField('First meeting')
	end_time = models.TimeField('End time', blank=True, null=True)
	additional_dates_text = models.TextField('Notes about additional meetings', blank=True)

	# locational
	location = models.ForeignKey(Location, blank=True, null=True, on_delete=models.SET_NULL, related_name='location')
	partner = models.ForeignKey(Partner, blank=True, null=True, on_delete=models.SET_NULL, related_name='partner')
	
	#TODO: `type' keyword is reserved, and using it is considered naughty.
	TYPE_CHOICES = (
		('CLASS', 'Class'),
		('EVENT', 'Event'),
		('EXTERNAL', 'Non-KCDC Event'),
	)
	type = models.CharField(max_length=9, choices=TYPE_CHOICES, default='CLASS')

	# descriptive text
	summary = models.TextField('Teaser', blank=True)
	description = models.TextField(blank=True)
	details = models.TextField('Pre-class details', blank=True)
	documentation = models.TextField(blank=True)
	
	# list view
	TN_SMALL = 'small'
	TN_LARGE = 'large'
	LIST_LAYOUT_CHOICES = (
		(TN_SMALL, 'Small'),
		(TN_LARGE, 'Large'),
	)
	list_layout = models.CharField(max_length=5, choices=LIST_LAYOUT_CHOICES, default=TN_SMALL)
	thumbnail = models.ImageField('Thumbnail (max 432px wide)', upload_to='event_images', blank=True, null=True)

	# detail view
	IMG_SMALL = 'small'
	IMG_LARGE = 'large'
	IMG_LAYOUT_CHOICES = (
		(IMG_SMALL, 'Small'),
		(IMG_LARGE, 'Large'),
	)
	img_layout = models.CharField(max_length=5, choices=IMG_LAYOUT_CHOICES, default=IMG_SMALL)
	main_image = models.ImageField('Main image (max 660px wide)', upload_to='event_images', blank=True, null=True)
	caption = models.TextField(blank=True)

	# email reminders
	email_welcome_text = models.TextField('Extra text for welcome email', blank=True)  
	email_reminder = models.BooleanField('Send reminder email?', default=True)  # unused
	email_reminder_text = models.TextField('Extra text for reminder email', blank=True)  # unused

	# student numbers and waitlist
	max_students = models.IntegerField('Max students', blank=True, null=True, default=999)
	waitlist_status = models.BooleanField('Use waitlist', default=True)
	
	# registration control
	REGISTRATION_STATUS_CHOICES = (
		('AUTO', 'Auto'),
		('ALLOW', 'Allow (+)'),
		('PREVENT', 'Prevent (-)'),
		('HIDE', 'Hide forms'),
	)
	registration_status = models.CharField(max_length=7, choices=REGISTRATION_STATUS_CHOICES, default='AUTO')
	registration_opens = models.DateTimeField(blank=True, null=True)

	# people associated with this class

kcdc3/apps/classes/templates/classes/event_archive.html
{% extends "classes/event_base.html" %}
{% load pinata_filters %}

{% block title %}
 / {% for session in selected_session %}{{ session.long_title }}{% endfor %}
{% endblock %}

{% block content %}

	<div id="hed">
		<h1>
			{% for session in selected_session %}
			{{ session.long_title | smartlines }}
			{% endfor %}
		</h1>
	</div>

	<div id="main">

		{% for session in selected_session %}
			<div class="local_intro">

				{{ session.description | smartlines | safe }}

				{% if session.documentation %}
					<p class="more_link"><a href="/classes/{{ session.slug }}/background">More about this session</a></p>
				{% endif %}

			</div>
		{% endfor %}

		<dl class="calendar">

		{% for event in events reversed %}

			{% if event.status == "PUBLISHED" %}

					{% ifchanged event.date.toordinal %}
						<dt>
							{{ event.date|date:"l" }}<br />
							<strong>{{ event.date|date:"j" }}</strong> {{ event.date|date:"F" }}
							{% ifchanged event.date.year %}
								<br />{{ event.date|date:"Y" }}
							{% endifchanged %}
						</dt>
					{% endifchanged %}
					<dd class="{% if event.type == "EXTERNAL" %}partner_event{% endif %}">
						<a href="/classes/{{ event.slug }}">
							<h3>
								{% if event.cancelled %}<i class="label-cancelled">Cancelled<br></i>{% endif %}
								{% if event.type == "EXTERNAL" %}<i>Community Calendar:</i>{% endif %}
								{{ event.title | smartlines }}
							</h3>
                            {% if event.additional_dates_text %}
					        <p class="meta">
					            <i class="ss-icon">&#x22C6;</i> Multipart class
					        </p>
					        {% endif %}
							<p class="meta">

								{% if event.type == "EVENT" %}
									<b class="event_type_indicator"><i class="ss-icon">&#x266B;</i> KCDC Event</b>
								{% endif %}

								<i class="ss-icon">time</i> {{ event.date|date:"P" }}

								{% if event.has_passed %}
									<!-- past event -->
								{% elif event.registration_status == "ALLOW" %}
									{% if event.registration_count >= event.max_students %}
									 	{% if event.waitlist_status %}
											<span class="registration_indicator"><i class="ss-icon registration_waitlist">&#xF071;</i> Waitlist</span>
										{% else %}
											<span class="registration_indicator"><i class="ss-icon registration_full">&#xF073;</i> Class is full</span>
										{% endif %}
									{% else %}
										<span class="registration_indicator"><i class="ss-icon registration_open">&#xF070;</i> Registration is open</span>
									{% endif %}
								{% elif event.registration_status == 'PREVENT' %}
									<span class="registration_indicator"><i class="ss-icon registration_full">&#xF073;</i> Registration is closed</span>
								{% endif %}
								{% if event.documentation %}
									<span class="registration_indicator documentation"><i class="ss-icon indicator_documentation">&#x1F4F7;</i> Documentation</span>
								{% endif %}

							</p>

							{% if event.thumbnail %}
								<div class="event_thumbnail {% if event.list_layout == 'small' %}event_thumbnail_small{% endif %}">
									<img src="/media/{{ event.thumbnail }}" alt="" class="" />
								</div>
							{% endif %}

							{{ event.summary | smartquotes | safe }}

                            {% if event.num_teachers > 0 %}
							<p>
								<i class="ss-icon">user</i> Instructor{{ event.num_teachers|pluralize }}: {% for bio in event.teacher_bios.all %}{% if not forloop.first %}, {% endif %}{{ bio.name }}{% endfor %}
								{% if event.teacher_text %}{{ event.teacher_text|safe }}{% endif %}
							</p>
                            {% endif %}
                            
						</a>
					</dd>

				{% endif %}

			{% endfor %}

		</dl>

	</div>

{% endblock %}



{% block sidebar_content %}

		<div class="sidebar_text sidebar_contrast">

			{% for session in selected_session %}
				{{ session.sidebar_text|safe }}
			{% endfor %}

		</div>

{% endblock %}

kcdc3/apps/classes/templates/classes/event_base.html
{% extends "base.html" %}

{% block sidebar %}

	<div id="sidebar" class="sidebar_section">

		<div class="local_nav">
			<ul>
				<li><a href="/classes#upcoming"><i class="ss-icon icon_decorative">&#x25B9;</i>Upcoming classes</a></li>
				<li><a href="/classes#past"><i class="ss-icon icon_decorative">&#x25B9;</i>Recent classes</a></li>
				{% for session in sessions reversed %}
					<li><a href="/classes/{{ session.slug }}"><i class="ss-icon icon_decorative">&#x25BB;</i>{{ session.title }}</a></li>
				{% endfor %}
			</ul>
		</div>
	
		{% block sidebar_content %}
		{% endblock %}

	</div>

{% endblock %}

kcdc3/apps/classes/templates/classes/event_session.html
{% extends "classes/event_base.html" %}

{% block title %}
 / {% for session in selected_session %}{{ session.long_title }}{% endfor %}
{% endblock %}

{% block content %}

	<div id="hed">
		<h1>
			{% for session in selected_session %}
			{{ session.long_title }}
			{% endfor %}
		</h1>
	</div>

	<div id="main">
	
		{% for session in selected_session %}

			{{ session.documentation|safe }}

			<p class="more_link"><a href="/classes/{{ session.slug }}">Class listings for this session</a></p>

		{% endfor %}

	</div>

{% endblock %}



{% block sidebar_content %}

		<div class="sidebar_text sidebar_contrast">

			{% for session in selected_session %}
				{{ session.sidebar_text|safe }}
			{% endfor %}

		</div>

{% endblock %}

kcdc3/apps/classes/templates/classes/event_social.html
{% extends "classes/event_base.html" %}
{% load pinata_filters %}

{% block title %}
 / {% for session in selected_session %}{{ session.long_title }}{% endfor %}
{% endblock %}

{% block content %}

	<div id="hed">
		<h1>
			{% for session in selected_session %}
			{{ session.long_title | smartlines }}
			{% endfor %}
		</h1>
	</div>

	<div id="main">

		{% for event in events reversed %}

			{% if event.status == "PUBLISHED" %}

                <hr>

                <p>
                    <strong>"{{ event.title | smartlines }}"</strong>
                    {{ event.date|date:"D n/j" }} at
                    {{ event.location.name }}{% if event.location.neighborhood %}, {{ event.location.neighborhood }}{% endif %}
                    http://knowledgecommonsdc.org/classes/{{ event.slug }}
                </p>
                
                <p>
                    {{ event.registration_count }} registered / 
                    {{ event.waitlist_count }} waitlist / 
                    {{ event.max_students }} seats
                    <a href="/classes/{{ event.slug }}">more</a>
                </p>

                <p>
                    {% if event.cancelled %}
            			This class is canceled
            		{% elif event.has_passed %}
            			Past event
            		{% elif event.registration_status == "HIDE" %}
            			No registration info
            		{% else %}
            			{% if event.registration_status == "AUTO" and not event.is_registration_open %}
            				Registration opens at {{ event.registration_opens|time:"P" }} on {{ event.registration_opens|date:"l, j F" }}
            			{% elif event.registration_status == "PREVENT" %}
            				Registration is closed.
            				No waitlist slots are available.
            			{% elif registration_count >=  event.max_students %}
            				{% if event.waitlist_status %}
            					This class is full, but there is a waitlist available.
            				{% else %}
            					This class is full.
            					No waitlist slots are available.
            				{% endif %}
            			{% else%}
                            Registration is open
            			{% endif %}
            		{% endif %}
                </p>

                <p>
                    {{ event.date|date:"P" }}
                </p>

                {% if event.thumbnail %}
                    <div class="event_thumbnail {% if event.list_layout == 'small' %}event_thumbnail_small{% endif %}">
                        <img src="/media/{{ event.thumbnail }}" alt="" class="" />
                    </div>
                {% endif %}

                {% if event.num_teachers > 0 %}
                    <p>
                        {% for bio in event.teacher_bios.all %}{% if not forloop.first %}, {% endif %}{{ bio.name }}{% endfor %}
                        {% for bio in event.teacher_bios.all %}{% if bio.twitter %}<a href="http://twitter.com/{{ bio.get_twitter }}">@{{ bio.get_twitter }} </a>{% endif %}{% endfor %}
                    </p>
                {% endif %}

            {% endif %}

		{% endfor %}

	</div>

{% endblock %}

{% block sidebar %}
{% endblock %}

kcdc3/apps/classes/templates/classes/response.html
{% extends "base.html" %}
{% load pinata_filters %}

{% block content %}

	{% if message = "registered" %}

		<h3>Thank you. You&rsquo;ve been registered.</h3>
		<p>We sent you a confirmation email with details about the class.</p>

		<!-- donation call -->
		<div style="margin-top: 2em; padding: 0.25em 1em 2em 1em; max-width: 440px; border: 1px solid #eee; ">
			<h4>Donate to {% boilerplate 'project_short_name' %}</h4>
			<p>
				This school relies on your support.
				A gift of even $10 will help us deliver superb, participatory classes all over the city.
			</p>
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick" /> <input type="hidden" name="hosted_button_id" value="H9ENKNZVLPU4W" /> <button class="button_link alt" type="submit">Donate now</button></form>
		</div>

	{% elif message = "waitlisted" %}
		<h3>You&rsquo;ve been added to the waitlist</h3>
		<p>We sent you a confirmation email with details about the class.</p>
	{% elif message = "cancelled" %}
		<h3>Thank you. We canceled your registration.</h3>
		<p>We sent you a confirmation email.</p>
	{% else %}
		{{ message }}
	{% endif %}

	<p style="margin-top: 4em;"><a class="button_link" href="/classes">Back to class list</a></p>

{% endblock %}

kcdc3/apps/classes/templates/classes/session_admin_list.html
{% block content %}
	
	<h2>Sessions</h2>	
	<table>
		<tr>
			<td>
			</td>
			<td>
				Session
			</td>
			<td>
				Slug
			</td>
			<td>
				Status
			</td>
			<td>
				Regular classes
			</td>
			<td>
				Registrations
			</td>
			<td>
				Attended
			</td>
		</tr>
	{% for session in session_list %}
		<tr>
			<td>
				<a href="/admin/classes/session/{{ session.id }}">Edit</a>
			</td>
			<td>
				<a href="/classes/{{ session.slug }}">{{ session.long_title }}</a>
			</td>
			<td>
				{{ session.slug }} 
			</td>
			<td>
				{{ session.status }} 
			</td>
			<td>
				{{ session.get_live_classes.count }}
			</td>
			<td>
				{{ session.get_registrations.count }}
			</td>
			<td>
				{{ session.get_attended_registrations.count }}
			</td>
			<td>
				<a href="/classes/staff/teachers/session/{{ session.slug }}">Teachers</a>
			</td>
			<td>
				<a href="/classes/staff/registrations/session/{{ session.slug }}">Registrations</a>
			</td>
		</tr>
	{% endfor %}
	</table>

	
{% endblock %}

kcdc3/apps/classes/templates/classes/staff_session_list.html
{% extends "classes/staff.html" %}


{% block content %}
		
	<hr />

	<h2>Sessions</h2>	
	<table>
		<tr>
			<td>
			</td>
			<td>
				Session
			</td>
			<td>
				Status
			</td>
			<td>
				Regular classes
			</td>
			<td>
				Registrations
			</td>
			<td>
				Attended
			</td>
			<td colspan="2">
				Reports
			</td>
			<td>
				Preformatted
			</td>
		</tr>
	{% for session in session_list %}
		<tr>
			<td>
				<a href="/admin/classes/session/{{ session.id }}">Edit</a>
			</td>
			<td>
				<a href="/classes/{{ session.slug }}">{{ session.long_title }}</a>
			</td>
			<td>
				{{ session.status }} 
			</td>
			<td>
				{{ session.get_live_classes.count }}
			</td>
			<td>
				{{ session.get_registrations.count }}
			</td>
			<td>
				{{ session.get_attended_registrations.count }}
			</td>
			<td>
				<a href="/classes/staff/teachers/session/{{ session.slug }}">Teachers</a>
			</td>
			<td>
				<a href="/classes/data/registration/session/{{ session.slug }}/csv/">Registrations (CSV)</a>
			</td>
			<td>
				<a href="/classes/staff/social/session/{{ session.slug }}">Social</a>
			</td>
		</tr>
	{% endfor %}
	</table>

	<hr />
	
	<p><a href="/classes/staff/teachers">All Teachers</a></p>

	
{% endblock %}